dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('info/edit/<int:id>/', views.editInfo, name="edit-page"), 
    path('update/edit/<int:id>/', views.editUpdate, name="edit-update-page"),
    path('update/create/', views.createUpdate, name="create-update-page"),
    path('update/<int:id>/delete/', views.deleteUpdate, name="delete-update"),
    path('photos/', views.photoUpload, name="upload-photos"),
    path('', views.dashboard, name="dashboard"),
]

info/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('summer-show/', views.SummerShow, name="summer-show"),
    path('toy-show/', views.ToyShow, name="toy-show"),
    path('scholarship/', views.Scholarship, name="scholarship"),
    path('golf-cart-policy/', views.GolfCart, name="golf-cart"),
    path('exhibitor-information/', views.ExhibitorInfo, name="exhibitor-info"),
    path('exhibitor-camping/', views.ExhibitorCamping, name="exhibitor-camping"),
    path('toy-vendor/', views.ToyVendor, name="toy-vendor"),
    path('food-vendor/', views.FoodVendor, name="food-vendor"),
    path('flea-market-vendor/', views.FleaMarket, name="flea-market"),
    path('directions/', views.Directions, name="directions"),
    path('contact/', views.Contact, name="contact"),
    path('club-members/', views.ClubInfo, name="club-info"),
]

photos/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.Photos, name="photos"),
]

winamacpowershow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="homepage"),
    path('info/', include('info.urls')),
    path('photos/', include('photos.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='dashboard/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='dashboard/logout.html'), name='logout'),
]

dashboard/models.py
from django.db import models

# Create your models here.

info/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone

# Create your models here.

class Info(models.Model):
    name = models.CharField(max_length=120)
    content = RichTextField()
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Info"
        
class Update(models.Model):
    name = models.CharField(max_length=120)
    content = RichTextField()
    created_at = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.name
    
    
        
        

photos/models.py
from django.db import models

# Create your models here.
class Set(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Image(models.Model):
    photo = models.ImageField(upload_to='Tractor Show', null=True)
    set = models.ForeignKey(Set, on_delete=models.CASCADE)

    def __str__(self):
        return self.photo.name

dashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from info.models import Info, Update
from photos.models import Image

class InfoForm(forms.ModelForm):
    class Meta:
        model = Info
        fields = ['name', 'content']
        
class UpdateForm(forms.ModelForm):
    class Meta:
        model = Update
        fields = ['name', 'content', 'created_at']
        
class PhotosForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['photo', 'set']

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import InfoForm, UpdateForm, PhotosForm
from info.models import Info, Update
from photos.models import Image

# Create your views here.

@login_required
def dashboard(request):
    info = Info.objects.all()
    update = Update.objects.order_by('-id').all()
    return render(request, 'dashboard/dashboard.html', {'info': info, 'update': update})
    
@login_required
def editInfo(request, id):
    page = Info.objects.get(id=id)
    if request.method == 'POST':
        form = InfoForm(request.POST, instance=page)
        if form.is_valid():
            form.save() 
    else:
        form = InfoForm(instance=page)
    return render(request, 'dashboard/info-edit.html', { 'form': form })


@login_required
def createUpdate(request):
    if request.method == 'POST':
        form = UpdateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
    else:
        form = UpdateForm()
    return render(request, 'dashboard/info-edit.html', {'form': form})

@login_required
def deleteUpdate(request, id):
    update = Update.objects.get(id=id).delete()
    return redirect('dashboard')
    
        
@login_required
def editUpdate(request, id):
    update = Update.objects.get(id=id)
    if request.method == 'POST':
        form = UpdateForm(request.POST, instance=update)
        if form.is_valid():
            form.save()  
    else:
        form = UpdateForm(instance=update)
    return render(request, 'dashboard/info-edit.html', {'form': form})

@login_required
def photoUpload(request):
    if request.method == 'POST':
        form = PhotosForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
    else:
        form = PhotosForm()
    return render(request, 'dashboard/photos.html', {'form': form})


        

info/views.py
from django.shortcuts import render
from .models import Info

# Create your views here.
def SummerShow(request):
    info = Info.objects.get(name="Summer Show Info")
    events = Info.objects.get(name="Summer Show Page Event Schedule")
    return render(request, 'info/summer_show.html', {'info': info, 'events': events})

def ToyShow(request):
    return render(request, 'info/toy_show.html')

def Scholarship(request):
    info = Info.objects.get(name="Northern Indiana Power from the Past Scholarships")
    return render(request, 'info/scholarship.html', {'info': info})
    
def GolfCart(request):
    info = Info.objects.get(name="Golf Cart Policy")
    return render(request, 'info/golf_cart.html', {'info': info})

def ExhibitorInfo(request):
    info = Info.objects.get(name="Exhibitor Information")
    return render(request, 'info/exhibitor_info.html', {'info': info})

def ExhibitorCamping(request):
    info = Info.objects.get(name="Camping for Exhibitors")
    return render(request, 'info/exhibitor_camping.html', {'info': info})

def ToyVendor(request):
    info = Info.objects.get(name="Toy Vendor Info")
    return render(request, 'info/toy_vendor.html', {'info': info})

def FoodVendor(request):
    info = Info.objects.get(name="Food Vendor Information")
    return render(request, 'info/food_vendor.html', {'info': info})

def FleaMarket(request):
    info = Info.objects.get(name="Flea Market Vendor Info")
    return render(request, 'info/flea_market.html', {'info': info})

def Directions(request):
    return render(request, 'info/directions.html')

def Contact(request):
    info = Info.objects.get(name="Contact Information")
    return render(request, 'info/contact.html', {'info': info})

def ClubInfo(request):
    members = Info.objects.get(name="Club Members")
    dates = Info.objects.get(name="Club Meeting Dates")
    return render(request, 'info/club_info.html', {'members': members, 'dates': dates})

photos/views.py
from django.shortcuts import render
from .models import Image, Set
# Create your views here.
def Photos(request):
    set = Set.objects.order_by('-id').all()
    return render(request, 'photos/photos.html', {'set': set})

winamacpowershow/views.py
from django.shortcuts import render
from info.models import Update

def index(request):
    update = Update.objects.order_by('-id').all()
    return render(request, 'winamacpowershow/index.html', {'update': update})

dashboard/templates/dashboard/dashboard.html
{% extends 'winamacpowershow/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Dashboard | {{ block.super }}
{% endblock title %}

{% block content %}
<h1>Dashboard</h1>

<div class="dashboard-content">
    
    
    <div class="informational">
        <h2>Informational Content</h2>
        <ul>
            {% for x in info %}
            <li>
                <a href="{% url 'edit-page' x.id %}">{{ x.name }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>


    <div class="update-edit">
        <h2>Updates</h2> 
        <a class="btn btn-sm btn-success" href="{% url 'create-update-page' %}">Create</a>
        
        <ul>
            {% for x in update %}
            <li>
                <div class="align-link">
                    <a href="{% url 'edit-update-page' x.id %}">{{ x.name }}</a>
                    -
                    <a class="delete" href="{% url 'delete-update' x.id %}">Delete</a>
                </div>                
            </li>
            {% endfor %}
        </ul>
    </div>

    
</div>

{% endblock content %}

dashboard/templates/dashboard/info-edit.html
{% extends 'winamacpowershow/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Edit info
{% endblock title %}

{% block content %}
<div class="edit-info">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ form.media }}
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

dashboard/templates/dashboard/login.html
{% extends 'winamacpowershow/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Login | {{ block.super }}
{% endblock title %}

{% block content %}
<div class="edit-info">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login</legend>
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

dashboard/templates/dashboard/logout.html
{% extends 'winamacpowershow/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Edit info
{% endblock title %}

{% block content %}
<div class="edit-info">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ form.media }}
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

dashboard/templates/dashboard/photos.html
{% extends 'winamacpowershow/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Upload Photos
{% endblock title %}

{% block content %}
<div class="edit-photos">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Upload Photos</legend>
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

info/templates/info/club_info.html
{% extends 'winamacpowershow/base.html' %}

{% block title %}
Club Members | {{ block.super }}
{% endblock title %}

{% block content %}
<div class="club-info">
    <h1 style="margin: .25em 0;">Current Club Members</h1>

    <div class="text-center">
        <button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#myModal">See upcoming meeting dates</button>
    </div>

    <h3 class="center">Click on the name to see mini-biography</h3>


        <div class="query-content">
            {{ members.content | safe }}
        </div>

    


    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title center">Meeting Dates</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body" style="text-align: center">
                    {{ dates.content | safe }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" style="margin: 0 auto; display: block;">Close</button>
                </div>
            </div>

        </div>
    </div>

</div>
{% endblock content %}

info/templates/info/contact.html
{% extends 'winamacpowershow/base.html' %}

{% block title %}
Contact | {{ block.super }}
{% endblock title %}

{% block content %}
<div class="contact-info">
	 <h1 style="margin: .25em 0;">{{ info.name }}</h1>
	 <div class="body">
		{{ info.content | safe }}
	 </div>
</div>
{% endblock content %}

info/templates/info/directions.html
{% extends 'winamacpowershow/base.html' %}

{% block title %}
Directions | {{ block.super }}
{% endblock title %}

{% block content %}
<div class="directions">
	<h1>Directions</h1>

	
	<div class="around">
		<div class="row">
			<div class="col-sm-12">
                <h2>Summer Show</h2>
			    <h4>10 City Park Drive<br> Winamac, IN 46996</h4>

				<iframe class="map" frameborder="0" src="https://www.google.com/maps/embed/v1/place?q=10%20City%20Par%20Drive%20Winamac%2C%20IN%2046996&key=AIzaSyCZfrvKZEGslRl7CkrXd7be7DVXLWBgVQU" allowfullscreen></iframe> 
			</div>
		</div>
	</div>
	<br>
	<div class="around">
		
		<div class="row">
			<div class="col-sm-12" id="toy-show">
                <h2>Toy Show</h2>
                <h4>815 School Drive<br> Winamac, IN 46996</h4>
				<iframe class="map"frameborder="0" src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJXRmaCZTCE4gRjgecZcnMO08&key=AIzaSyDkhINotnhDTvY0l6P72Omwt968XO0u7Q8" allowfullscreen></iframe>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

info/templates/info/exhibitor_camping.html
{% extends 'winamacpowershow/base.html' %}

{% block title %}
Exhibitor Camping | {{ block.super }}
{% endblock title %}

{% block content %}
<div class="info">
	 <h1>{{ info.name }}</h1>
	 <div class="body">
		{{ info.content | safe }}
	 </div>
</div>
{% endblock content %}

info/templates/info/exhibitor_info.html
{% extends 'winamacpowershow/base.html' %}

{% block title %}
Exhibitor Information | {{ block.super }}
{% endblock title %}

{% block content %}
<div class="info">
	 <h1>{{ info.name }}</h1>
	 <div class="body">
		{{ info.content | safe }}
	 </div>
</div>
{% endblock content %}

info/templates/info/flea_market.html
{% extends 'winamacpowershow/base.html' %}

{% block title %}
Flea Market | {{ block.super }}
{% endblock title %}

{% block content %}


<div class="info">
	 <h1>{{ info.name }}</h1>
	 <div class="body">
		{{ info.content | safe }}
	 </div>
</div>

<!-- Modal -->
<div id="contract" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-body">
        <h2>IMPORTANT!</h2>
        <h5><strong>You MUST contact the director in charge before sending in a contract.</strong></h5>

        <p>There are many advance reservations and those who send in a contract without prior approval are NOT guaranteed a spot.  We look forward to returning vendors and also new ones'  Please call Rachelle Ortman at (574)946-3206</p>

      </div>
      <div class="modal-footer">
        <button class="btn btn-success view-button"><a href="https://winamac.s3.us-east-2.amazonaws.com/Tractor+Show/NIPFTP+Summer+Show+Flea+Market+Contract+with+%24.pdf">I understand and wish to view the contract</a></button>
        <button type="button" class="btn btn-default btn-primary close-button" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<script>
$(document).ready(function(){

    $('.contract').html('<button type="button" class="btn btn-success btn-md" data-toggle="modal" data-target="#contract">View Contract</button>').css('margin-bottom', '.5em');

});  
</script>


{% endblock content %}

info/templates/info/food_vendor.html
{% extends 'winamacpowershow/base.html' %}

{% block title %}
Food Vendor | {{ block.super }}
{% endblock title %}

{% block content %}
<div class="info">
	 <h1>{{ info.name }}</h1>
	 <div class="body">
		{{ info.content | safe }}
	 </div>
</div>
{% endblock content %}

info/templates/info/golf_cart.html
{% extends 'winamacpowershow/base.html' %}

{% block title %}
Golf Cart Policy | {{ block.super }}
{% endblock title %}

{% block content %}
<div class="golf-cart">
	 <h1>{{ info.name }}</h1>
	 <div class="body">
		{{ info.content | safe }}
	 </div>
</div>
{% endblock content %}

info/templates/info/scholarship.html
{% extends 'winamacpowershow/base.html' %}

{% block title %}
Scholarship | {{ block.super }}
{% endblock title %}

{% block content %}
<h2 style="margin-top: .5em;">{{ info }}</h2>
{{ info.content | safe }}
{% endblock content %}

info/templates/info/summer_show.html
{% extends 'winamacpowershow/base.html' %}

{% block title %}
Summer Show | {{ block.super }}
{% endblock title %}

{% block content %}
	<div class="summer-head">
		<div class="row">
			<div class="col-lg-6">
				<div class="info2">
					<h1>43rd Summer Show!</h1>
					
						<h4 class="weekend">3rd Weekend in July</h4>
					
						<div class="btn btn-primary btn-md upcoming" data-toggle="modal" data-target="#myModal">Upcoming show dates</div>
						<!-- Modal -->
						<div class="modal fade" id="myModal" role="dialog">
							<div class="modal-dialog">
							
								<!-- Modal content-->
								<div class="modal-content">
									<div class="modal-header">
                                        <h4 class="modal-title">Upcoming Dates</h4>
										<button type="button" class="close" data-dismiss="modal">&times;</button>
									</div>
									<div class="modal-body text-left center-modal">
										<p>2021 July 15-18---Moline</p>
										<p>2022 July 14-17---John Deere</p>
										<p>2023 July 13-16---Allis & Rumley</p>
										<p>2024 July 18-21---Oliver</p>
										<p>2025 July 17-20---Odd Balls</p>
										<p>2026 July 16-19---Case</p>
										<p>2027 July 14-17---International</p>
										<p>2028 July 20-23---Cockshutt</p>
										<!--<p>2029 July 20-23---Moline</p>-->
										<small>Disclaimer: Featured tractors subject to change upon collector requests</small>
									</div>
									<div class="modal-footer">
										<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
									</div>
								</div>
							
							</div>
						</div>
				
					
					<h4 style="margin-top: 10px;"><strong>July 15th, 16th, 17th, 18th 2021</strong></h4>
					<h3>At the Winamac Town Park</h3>
					<a href="#summer-directions"><h4 class="bold">10 City Park Drive<br>
						Winamac IN, 46996</h4></a>
					<h5>Daily Adult Admission: $3.00</h5>
					<h5>4 Day Pass: $9.00</h5>
					<h5>(Children Under 12 free when accompanied by an adult)</h5>
					
					<a href="https://winamac.s3.us-east-2.amazonaws.com/Tractor+Show/PwrShow2021.pdf" button type="button" class="btn btn-success btn-lg flyer-button" style= "width: 15em;">Summer Show Flyer</a>
					
				</div>
			</div>
			<div class="col-lg-6">
				<div class="info1">
					<img class="event-image" src="https://winamac.s3.us-east-2.amazonaws.com/Tractor+Show/img_6368.jpg">
				</div>
			</div>
		</div>
	</div>
	
	

	<div class="blurb">

		<p>The Northern Indiana Power from the Past would be thrilled to have you at our summer show.  Come for a few hours or stay the whole day.  There is plenty to see and do.  We feature moving displays where you can see real antique farm machinery in action, doing what it was designed to do.  </p>
        
        <p>Each year we choose a different equipment manufacturer to highlight and put those tractors front and center in our display area.  We are ALWAYS an "all color" show and like to have all manufacturers' equipment represented every year.</p>
		
		<p>There are also many interesting stationary displays where you can take your time and look come and get and up close look at what was used in early agriculture.</p>
		
		<p>There are several buildings and outdoor areas are stuffed with flea marketers.  The incredible variety of old and new items they bring to sell is almost overwhelming.  Allow some time to browse them all and bring home a treasure.</p>
		
		<p>What event would be complete without food?  Over a dozen different food vendors are here to serve you something tasty.   Have a no cook day.  Come for breakfast, lunch, and dinner.</p>
		
		<p>If you’re in the mood for some great music and maybe some dancing, this is your place.  We feature different entertainment daily. Check out the daily tabs on the website to see what we have.  Looking just to relax and watch others perform?  The very popular horse pull, hilarious tractor square dancing, or the classic car cruise-in might be for you.  This is a family show, we didn’t forget about your young ones.  Kids have their own games every day too!</p>
		
		<p>How much does it cost to attend? Not $20, not $15, not $10. No, not even $5.  Only $3.00 for adults and kids under 12 years old are FREE!  The entertainment is even included in this price.  It’s a deal you can’t pass up.  Can’t wait to see you there!</p>				
		
	</div>
	
	

	<div class="events" style="margin-bottom: 1em;">
		<h2>Daily Events - Starting at 10:00 A.M. Everyday</h2>
		<h4 class="underline">All times are in Eastern time zone</h4>
		<table class="daily-events">
			<thead>
				<th colspan="3"><h4>Flag Raising/National Anthem kicks off each day at 9:00 A.M.</h4></th>
			</thead>
			<tbody>
				<tr>
					<td>Antiques & Collectibles</td>
					<td>Corn Shredder</td>
					<td>Threshing</td>
				</tr>
				<tr>
					<td>Sawmill</td>
					<td>Steam Engines</td>
					<td>Quilt Show</td>
				</tr>
				<tr>
					<td>Flea Market</td>
					<td>Baker Fan</td>
					<td>Barn Beam Drill</td>
				</tr>
				<tr>
					<td>Wood Planer</td>
					<td>Horse & Wagon Rides</td>
					<td>Pottery</td>
				</tr>
				<tr>
					<td>Corn Sheller</td>
					<td>Print Shop</td>
					<td>Blacksmith</td>
				</tr>
				<tr>
					<td>Shingle Mill</td>
					<td>Buzz Saw</td>
					<td>Baling</td>
				</tr>
				<tr>
					<td colspan="3">1:30 P.M. - Daily - Children's Games (Dress appropriately) </td>
				</tr>
				<tr>
					<td>Horse Sweep</td>
					<td>Wooden Bowls</td>
					<td>Crosscut Saw Contests</td>
				</tr>
				<tr>
					<td colspan="3">Every day we break for lunch - Listen for the steam engine whistles</td>
				</tr>
			</tbody>
		</table>
	</div>

	<script>
		$(document).ready(function(){
			$("div.summer-schedule").find("ul").addClass("list-group");
			$("div.summer-schedule").find("ul").children("li").addClass("list-group-item");

			
		});
	</script>

{{ events.content | safe }}

	<div class="summer-show-info">
        <div class="summer-map">
			<h1>Summer Show Map</h1>
			<img src="https://winamac.s3.us-east-2.amazonaws.com/Tractor+Show/summer-map.png">
		</div>
        
		<h1>{{ info.name }}</h1>
		<div class="body">
		   {{ info.content | safe }}
		</div>
		
        <div id="summer-directions">
            <h2><strong>Directions</strong></h2>
            <h4>10 City Park Drive<br> Winamac, IN 46996</h4>

            <iframe class="map" frameborder="0" src="https://www.google.com/maps/embed/v1/place?q=10%20City%20Par%20Drive%20Winamac%2C%20IN%2046996&key=AIzaSyCZfrvKZEGslRl7CkrXd7be7DVXLWBgVQU" allowfullscreen></iframe> 
        </div>

	</div>

{% endblock content %}

info/templates/info/toy_vendor.html
{% extends 'winamacpowershow/base.html' %}

{% block title %}
Food Vendor | {{ block.super }}
{% endblock title %}

{% block content %}
<div class="info">
	 <h1>{{ info.name }}</h1>
	 <div class="body">
		{{ info.content | safe }}
	 </div>
</div>
{% endblock content %}

photos/templates/photos/photos.html
{% extends 'winamacpowershow/base.html' %}

{% block title %}
Photos | {{ block.super }}
{% endblock title %}

{% block content %}

<div class="photos">
    <h1 style="margin: .25em 0;">Photos</h1>
    <h5 class="center">Click on photo to enlarge</h5>
    <div class="image-display">
        {% for display in set %}
            <div class="image-set">
                <h2>{{ display.name }}</h2>
                {% for im in display.image_set.all %}
                    <a href="#/" class=" meat" data-img="{{ im.photo.url }}">
                        <img src="{{ im.photo.url }}">
                    </a>
                {% endfor %}
            </div>

        {% endfor %}
    </div>
</div>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <img src="" id="ModalImg" width="100%">
          </div>
        </div>
    </div>
</div>

<script>
$(window).resize(function (e) {
  window.resizeEvt;
  $(window).resize(function () {
    clearTimeout(window.resizeEvt);
    window.resizeEvt = setTimeout(function () {
      doneresizing();
    }, 250);
  });
});

$(function doneresizing() {
  $('img').click(function (){
    if( ($(window).width() <= 768) | /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
      event.preventDefault();
      alert('mobile! No links workinf');
    } else {
      $('#ModalImg').attr('src', $(this).data('img'));
      $('#myModal').modal({show:true})
    }
  });
});
</script>
{% endblock content %}

winamacpowershow/templates/winamacpowershow/index.html
{% extends "winamacpowershow/base.html" %}
{% load static %}

{% block jumbotron %}

<div class="jumbotron">
  <img src="{% static 'winamacpowershow/POP.png' %}">
</div>

<div class="ribbon">
    <a href="{% url 'summer-show' %}">
        <h3>2021 Summer Show Dates July 15th, 16th, 17th, 18th</h3>
    </a>
</div>

{% endblock jumbotron %}

{% block content %}

    {% if update %}
    <div class="update-container">
        <h2>Stay Updated</h2>
        <div class="update">
            {% for x in update %}
            <div class="section">
                <h3><strong>{{ x.name }}</strong></h3>
                <h4>{{ x.created_at }}</h4>
                {{ x.content | safe }}
            </div>
            <hr>
            {% endfor %}
        </div>
        <div class="scroll-notice">
            Scroll to see more
        </div>
    </div>

    <hr>
    {% endif %}
   
    <div class="tractor-brand">
            <h2>Featuring Minneapolis Moline</h2>
            <img src="{% static 'winamacpowershow/moline.jpg' %}">
    </div>

    <hr>
    <div class="philosophy">
        <h2>Philosophy of the Northern Indiana Power from the Past, Inc.</h2>
        <p>The functional purpose of this corporation is to preserve, rejuvenate, and display antique farm machinery and any other form of machinery utilized in the growth of the U.S.A. Futher, it is the intention of the corporation to foster and perpetuate in the minds of all Americans respect, interest, and recognition of the vital role that different forms of machinery, no matter what their power source, have played in the development of our society as a whole.</p>
    </div><hr>
    <div class="scholarships">
        <h2>Scholarships</h2>
        <p>Up to three scholarships are available to high school seniors going into agricultural trades.  <a href="{% url 'scholarship' %}">Find out more!</a></p>
    </div>
{% endblock content %}